/**
 * Build the GAA Stage-B summary layer for D1.
 *
 * The four largest departments cannot ship Stage B as one response — DPWH is
 * 1,192,606 rows and the Worker dies serialising it (Cloudflare 1102). The
 * interactive mode serves those views from small precomputed tables plus
 * per-level drill queries instead. This script materialises the two
 * aggregates the views need, straight from the same SQLite that feeds D1:
 *
 *   gaa_fpap_families        program families: fpaps grouped per agency by
 *                            normalised name (the "merged across renames"
 *                            grouping the client computes in dept-data.ts)
 *   gaa_dept_expense_classes per-agency expense-class totals per year
 *
 * Semantics are a 1:1 port of loadDeptMidInto:
 *   - normName: lowercase, collapse whitespace, strip [^a-z0-9 ], trim
 *   - rows whose description or slug is the literal "nan" are excluded
 *   - family name = description of the lowest id (the client takes the first
 *     row in id order)
 *   - families whose amounts sum to zero across all years are dropped
 *   - amounts stay in SOURCE THOUSANDS, like every other entity table; the
 *     client rescales
 *
 * Also emits the one index the measurements justified: objects
 * (department_id, amount_2026 DESC, id) — the objects/page default sort was
 * paying a 995k-row temp sort (~1.3s) per page for DepEd.
 *
 * Output: data/gaa-summaries.sql (idempotent; only touches gaa_* objects and
 * the new objects index). Apply with:
 *   npx wrangler d1 execute budget --local  --file=data/gaa-summaries.sql
 *   npx wrangler d1 execute budget --remote --file=data/gaa-summaries.sql
 */

import { DuckDBInstance } from "@duckdb/node-api";
import { createWriteStream } from "node:fs";
import { stat } from "node:fs/promises";
import { globSync } from "node:fs";
import { resolve } from "node:path";

const YEARS = [2020, 2021, 2022, 2023, 2024, 2025, 2026] as const;
const OUT = resolve("data/gaa-summaries.sql");
/** D1 rejects statements over 100KB; DPWH road-project names are long, so
    batch by bytes with headroom rather than by row count. */
const BATCH_BYTES = 80_000;

/** Mirrors normName() in src/lib/dept-data.ts exactly. */
const NORM = (col: string) =>
  `trim(regexp_replace(regexp_replace(lower(coalesce(${col}, '')), '\\s+', ' ', 'g'), '[^a-z0-9 ]', '', 'g'))`;

/** Mirrors isNan() in src/lib/dept-data.ts. */
const NOT_NAN = `lower(coalesce(description,'')) <> 'nan' AND coalesce(slug,'') <> 'nan'`;

const yearCols = (kind: "amount" | "count") => YEARS.map((y) => `${kind}_${y}`);
const allYearCols = [...yearCols("amount"), ...yearCols("count")];

const lit = (expr: string) =>
  `CASE WHEN ${expr} IS NULL THEN 'NULL' ELSE '''' || replace(${expr}, '''', '''''') || '''' END`;

async function writeBatched(
  w: (s: string) => Promise<void>,
  table: string,
  rows: string[],
): Promise<void> {
  let batch: string[] = [];
  let bytes = 0;
  const flush = async () => {
    if (!batch.length) return;
    await w(`INSERT INTO ${table} VALUES ${batch.join(",")};\n`);
    batch = [];
    bytes = 0;
  };
  for (const r of rows) {
    if (bytes + r.length > BATCH_BYTES) await flush();
    batch.push(r);
    bytes += r.length + 1;
  }
  await flush();
}

async function main() {
  const dbFiles = globSync(
    ".wrangler/state/v3/d1/miniflare-D1DatabaseObject/*.sqlite",
  ).filter((f) => !f.endsWith("metadata.sqlite"));
  if (!dbFiles.length) throw new Error("local D1 sqlite not found — run the D1 loads first");

  const db = await DuckDBInstance.create(":memory:");
  const c = await db.connect();
  await c.run(`INSTALL sqlite; LOAD sqlite;`);
  await c.run(`ATTACH '${dbFiles[0].replace(/'/g, "''")}' AS d1 (TYPE sqlite, READ_ONLY)`);

  const out = createWriteStream(OUT);
  const w = (s: string) =>
    out.write(s) ? Promise.resolve() : new Promise<void>((r) => out.once("drain", () => r()));

  await w(`-- GAA Stage-B summary layer. Generated by scripts/build-gaa-summaries.ts.\n`);
  await w(`-- Additive: only gaa_* tables and one objects index. Amounts in SOURCE THOUSANDS.\n\n`);
  await w(`DROP TABLE IF EXISTS gaa_fpap_families;\n`);
  await w(`DROP TABLE IF EXISTS gaa_dept_expense_classes;\n\n`);
  await w(`CREATE TABLE gaa_fpap_families (
  department_id TEXT NOT NULL,
  agency_id     TEXT NOT NULL,
  fam_key       TEXT NOT NULL,
  name          TEXT NOT NULL,
  ids_count     INTEGER NOT NULL,
${allYearCols.map((k) => `  ${k} ${k.startsWith("amount") ? "REAL" : "INTEGER"}`).join(",\n")},
  PRIMARY KEY (department_id, fam_key)
);\n`);
  await w(`CREATE INDEX gaa_fpap_families_amt26_idx ON gaa_fpap_families(department_id, amount_2026 DESC);\n`);
  await w(`CREATE INDEX gaa_fpap_families_agency_idx ON gaa_fpap_families(agency_id);\n\n`);
  await w(`CREATE TABLE gaa_dept_expense_classes (
  department_id TEXT NOT NULL,
  agency_id     TEXT NOT NULL,
  expense_code  TEXT NOT NULL,
${allYearCols.map((k) => `  ${k} ${k.startsWith("amount") ? "REAL" : "INTEGER"}`).join(",\n")},
  PRIMARY KEY (department_id, agency_id, expense_code)
);\n\n`);
  // The one index the EXPLAIN/timing review justified. Default-year objects
  // paging becomes an index walk instead of a 995k-row temp sort.
  await w(`DROP INDEX IF EXISTS objects_dept_amt26_idx;\n`);
  await w(`CREATE INDEX objects_dept_amt26_idx ON objects(department_id, amount_2026 DESC, id);\n\n`);

  // ---- families ------------------------------------------------------------
  const famSums = YEARS.flatMap((y) => [
    `coalesce(sum(coalesce(amount_${y}, 0)), 0) AS amount_${y}`,
    `coalesce(sum(coalesce(count_${y}, 0)), 0) AS count_${y}`,
  ]).join(",\n             ");
  const famValues = await c.runAndReadAll(`
    WITH fam AS (
      SELECT department_id,
             agency_id,
             agency_id || '|' || ${NORM("description")} AS fam_key,
             arg_min(description, id) AS name,
             count(*) AS ids_count,
             ${famSums}
      FROM d1.fpaps
      WHERE ${NOT_NAN}
      GROUP BY department_id, agency_id, fam_key
    )
    SELECT '(' || ${lit("department_id")} || ',' || ${lit("agency_id")} || ',' || ${lit("fam_key")}
        || ',' || ${lit("name")} || ',' || ids_count
        || ',' || ${allYearCols.map((k) => `${k}::VARCHAR`).join(` || ',' || `)}
        || ')' AS v
    FROM fam
    WHERE ${YEARS.map((y) => `amount_${y}`).join(" + ")} > 0
    ORDER BY department_id, fam_key
  `);
  const famRows = famValues.getRows().map((r) => String(r[0]));
  await writeBatched(w, "gaa_fpap_families", famRows);
  process.stdout.write(`  gaa_fpap_families: ${famRows.length.toLocaleString()} rows\n`);

  // ---- expense classes -----------------------------------------------------
  const ecValues = await c.runAndReadAll(`
    WITH ec AS (
      SELECT department_id, agency_id, expense_code,
             ${famSums}
      FROM d1.expenses
      WHERE ${NOT_NAN} AND expense_code IN ('1','2','3','6')
      GROUP BY 1, 2, 3
    )
    SELECT '(' || ${lit("department_id")} || ',' || ${lit("agency_id")} || ',' || ${lit("expense_code")}
        || ',' || ${allYearCols.map((k) => `${k}::VARCHAR`).join(` || ',' || `)}
        || ')' AS v
    FROM ec ORDER BY department_id, agency_id, expense_code
  `);
  const ecRows = ecValues.getRows().map((r) => String(r[0]));
  await writeBatched(w, "gaa_dept_expense_classes", ecRows);
  process.stdout.write(`  gaa_dept_expense_classes: ${ecRows.length.toLocaleString()} rows\n`);

  await new Promise<void>((res, rej) => { out.once("error", rej); out.end(() => res()); });
  const sz = (await stat(OUT)).size;
  process.stdout.write(`wrote ${OUT} (${(sz / 1e6).toFixed(1)} MB)\n`);
  c.closeSync();
  db.closeSync();
}

main().catch((e) => { console.error(e); process.exit(1); });
